language: csharp
solution: Oware.sln
mono: none
jobs:
  include:
    - dotnet: 5.0
    - dotnet: 2.1.502
    
script:
    - dotnet --info
    - sudo snap install dotnet-sdk-5.0
    - sudo apt-get install dotnet-sdk-5.0
    - dotnet test Oware.Tests
os:
    - focal
    - osx
