language: csharp
solution: Oware.sln
mono: none
jobs:
  include:
    - dotnet: 5.0.203
    
script:
    - dotnet --info
    - snap install dotnet-sdk
    - sudo apt install dotnet-sdk
    - dotnet test Oware.Tests
os:
    - focal
    - osx
