language: csharp
solution: Oware.sln
mono: none
jobs:
  include:
    - dotnet: 5.0
    - dotnet: 2.1.502

script:
    - sudo snap install dotnet-sdk
    - dotnet test Oware.Tests
os:
    - linux
    - osx


dist: focal
